# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = 'https://mnovotny.net/'

# The name of this wonderful theme ;-).
theme = 'hugo-bearblog'

# Basic metadata configuration for your blog.
title = "Marek's personal webpage"
author = 'Marek Novotný'
copyright = '© Marek Novotný, 2025'
languageCode = 'en-us'

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Enable Git info for better content management
enableGitInfo = true

# Improve performance with minification in production
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false

# Configure permalinks for better URLs
[permalinks]
  publications = "/publications/:slug/"
  talks = "/talks/:slug/"

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "Personal webpage of Marek Novotný - Social geography student, GIS specialist, and open-source router developer at CZ NIC."

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "images/favicon.png"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  images = ["images/share.png"]

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "Marek Novotný"

  # This theme will, by default, inject a made-with-line at the bottom of the page.
  # You can turn it off, but we would really appreciate if you don't :-).
  # hideMadeWithLine = true

  # By default, this theme displays dates with a format like "02 Jan, 2006", but
  # you can customize it by setting the `dateFormat` param in your site's config
  # file. See [Hugo's Format function docs](https://gohugo.io/functions/format/)
  # for details. An example TOML config that uses [ISO
  # 8601](https://en.wikipedia.org/wiki/ISO_8601) format:
  dateFormat = "2006-01-02"

# Configure markup for better code highlighting and content processing
[markup]
  [markup.highlight]
    style = 'github'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Configure taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Configure menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 2
  [[menu.main]]
    name = "Talks"
    url = "/talks/"
    weight = 3

# Configure security headers (for static site hosting)
[security]
  [security.exec]
    allow = ["^(dart-)?sass(-embedded)?$", "^go$", "^npx$", "^postcss$"]
  [security.funcs]
    getenv = ["^HUGO_", "^CI$"]

# Configure caching for better performance
[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10s"
  [caches.getcsv]
    dir = ":cacheDir/:project"
    maxAge = "10s"
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "720h"
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = "720h"

# Configure server for local development
[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      Referrer-Policy = "strict-origin-when-cross-origin"
      Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; img-src 'self' data:; font-src 'self'"